### ISSUE TITLE
vm: Console toggling should be configurable

### ISSUE THREAD

**Issue by simon-whitehead** [simon-whitehead/hakka#11]
The console is currently toggled via the `Grave` key (the key under Escape. That is the tilde `~` on English keyboards).

Non-English keyboards struggle using this as the key to toggle the Console and so it would be great if this was configurable for users.

I am keen to [use the app_dirs crate](https://crates.io/crates/app_dirs) when figuring out where we should store user configuration files. I am not too concerned with the format of the files, although I imagine JSON is probably the best approach.

**Comment by seventh-chord** [comment]
Looking into this ATM

**Comment by simon-whitehead** [comment]
Awesome! Thanks @seventh-chord !!

Just as a side note, I would expect this to be part of the `vm` crate so that it can be re-used across levels. The `VirtualMachine` and `Console` types will hopefully be used in each new level that is added.

**Comment by seventh-chord** [comment]
I have moved it already, just forgot to reference the issue in the commit :) Should the code for locating the config file (using `app_dirs`) also be located in the config crate? Currently the path and ´Configuration´ is created in ´main.rs´, and passed to the console

**Comment by simon-whitehead** [comment]
I think its best if it lives in the the `vm` crate in the `config` module. Ideally the levels don't have to worry about the config file at all - they can just create a `VirtualMachine` instance, which creates a `Console` instance, which loads the configuration file.

**Comment by simon-whitehead** [comment]
That gives me an idea actually - the `Console` instance is currently created in the training level `main.rs` file. This should be moved into the `VirtualMachine`. I will add an issue for that as well!
